# Data Preprocessing
In this file, we will preprocess and prepare the 'Auto-MPG' dataset for use with the rest of the classification data.

Then, we will split this data into training and testing data.

### Imports

In [15]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn

import struct

sns.set_theme()

### Data Explanation
- mpg (target) - the miles traveled per gallon of gas for the given car, a measure of travel efficiency
- displacement (feature) - the total volume of air and fuel moved by the engine's pistons per cycle for the given car, measured in cubic centimeters
- cylinders (feature) - The number of cylinders that the given car's engine has
- horsepower (feature) - The horsepower of the engine of the given car
- weight (feature) - The weight of the given car.
- acceleration (feature) - The maximum acceleration of the given car.
- model_year (feature) - The initial production year of the given car model.
- is_USA (feature) - Whether the given car was produced in the USA. 1 if it was, 0 if not.
- is_Europe (feature) - Whether the given car was produced in the Europe. 1 if it was, 0 if not.
- is_Japan (feature) - Whether the given car was produced in the Japan. 1 if it was, 0 if not.

### Data Preprocessing
First, we will load in the data, assigning columns accordingly:

In [16]:
data_dir = "/home/patrick/Projects/DataScienceAndMachineLearning/Data/"

names = ["mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model_year", "origin", "car_name"]
df = pd.read_table(data_dir + 'auto-mpg.data', sep = r'\s+', names=names)
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

Drop the car name column:

In [17]:
df = df.drop(columns=["car_name"])
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504.0,12.0,70,1
1,15.0,8,350.0,165.0,3693.0,11.5,70,1
2,18.0,8,318.0,150.0,3436.0,11.0,70,1
3,16.0,8,304.0,150.0,3433.0,12.0,70,1
4,17.0,8,302.0,140.0,3449.0,10.5,70,1
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1
394,44.0,4,97.0,52.00,2130.0,24.6,82,2
395,32.0,4,135.0,84.00,2295.0,11.6,82,1
396,28.0,4,120.0,79.00,2625.0,18.6,82,1
397,31.0,4,119.0,82.00,2720.0,19.4,82,1

Now, one hot encode the origin column, as it is categorical with only three entries:

In [18]:
df["is_USA"] = (df["origin"] == 1).astype(np.int64)
df["is_Europe"] = (df["origin"] == 2).astype(np.int64)
df["is_Japan"] = (df["origin"] == 3).astype(np.int64)
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,is_USA,is_Europe,is_Japan
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,1,0,0
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,1,0,0
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,1,0,0
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,1,0,0
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,1,0,0
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,0,1,0
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,1,0,0
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,1,0,0
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,1,0,0

Replace '?' entries in the horsepower column with the mean horsepower, so that we will not have to drop those columns:

In [19]:
df["horsepower"] = df["horsepower"].replace("?", np.nan).astype(np.float64)
meanval = df["horsepower"].mean()
df["horsepower"] = df["horsepower"].fillna(meanval)
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,is_USA,is_Europe,is_Japan
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,1,0,0
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,1,0,0
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,1,0,0
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,1,0,0
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790.0,15.6,82,1,1,0,0
394,44.0,4,97.0,52.0,2130.0,24.6,82,2,0,1,0
395,32.0,4,135.0,84.0,2295.0,11.6,82,1,1,0,0
396,28.0,4,120.0,79.0,2625.0,18.6,82,1,1,0,0
397,31.0,4,119.0,82.0,2720.0,19.4,82,1,1,0,0

Finally, drop remaining useless columns:

In [20]:
df = df.drop(columns=["origin", "model_year"])
df = df.astype(np.float64)
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,is_USA,is_Europe,is_Japan
0,18.0,8.0,307.0,130.0,3504.0,12.0,1.0,0.0,0.0
1,15.0,8.0,350.0,165.0,3693.0,11.5,1.0,0.0,0.0
2,18.0,8.0,318.0,150.0,3436.0,11.0,1.0,0.0,0.0
3,16.0,8.0,304.0,150.0,3433.0,12.0,1.0,0.0,0.0
4,17.0,8.0,302.0,140.0,3449.0,10.5,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
393,27.0,4.0,140.0,86.0,2790.0,15.6,1.0,0.0,0.0
394,44.0,4.0,97.0,52.0,2130.0,24.6,0.0,1.0,0.0
395,32.0,4.0,135.0,84.0,2295.0,11.6,1.0,0.0,0.0
396,28.0,4.0,120.0,79.0,2625.0,18.6,1.0,0.0,0.0
397,31.0,4.0,119.0,82.0,2720.0,19.4,1.0,0.0,0.0

In [ ]:
for col in df.columns:
    df[col] = (df[col] - df[col].mean()) / df[col].std()
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,is_USA,is_Europe,is_Japan
0,-0.705551,1.496308,1.089233,0.668355,0.630077,-1.293870,0.772587,-0.461387,-0.497018
1,-1.089379,1.496308,1.501624,1.584605,0.853259,-1.475181,0.772587,-0.461387,-0.497018
2,-0.705551,1.496308,1.194728,1.191926,0.549778,-1.656492,0.772587,-0.461387,-0.497018
3,-0.961437,1.496308,1.060461,1.191926,0.546236,-1.293870,0.772587,-0.461387,-0.497018
4,-0.833494,1.496308,1.041280,0.930141,0.565130,-1.837804,0.772587,-0.461387,-0.497018
...,...,...,...,...,...,...,...,...,...
393,0.445936,-0.855244,-0.512381,-0.483502,-0.213056,0.011571,0.772587,-0.461387,-0.497018
394,2.620966,-0.855244,-0.924773,-1.373573,-0.992422,3.275173,-1.291101,2.161930,-0.497018
395,1.085650,-0.855244,-0.560333,-0.535859,-0.797581,-1.438919,0.772587,-0.461387,-0.497018
396,0.573879,-0.855244,-0.704191,-0.666752,-0.407897,1.099439,0.772587,-0.461387,-0.497018
397,0.957708,-0.855244,-0.713781,-0.588216,-0.295716,1.389537,0.772587,-0.461387,-0.497018

### Train / Test Split
First, set train/test split parameters:

In [30]:
train_test_ratio = 0.7
train_cutoff = round(train_test_ratio * df.shape[0])

Now, perform the split:

In [31]:
X_data = df.iloc[:, 1:].to_numpy()
y_data = df.iloc[:, 0].to_numpy()
train_X = df.iloc[:train_cutoff, 1:].to_numpy()
test_X = df.iloc[train_cutoff:, 1:].to_numpy()
train_y = df.iloc[:train_cutoff, 0].to_numpy()
test_y = df.iloc[train_cutoff:, 0].to_numpy()
train_X

array([[ 1.49630792,  1.08923273,  0.66835485, ...,  0.77258661,
        -0.46138749, -0.49701778],
       [ 1.49630792,  1.50162428,  1.58460471, ...,  0.77258661,
        -0.46138749, -0.49701778],
       [ 1.49630792,  1.19472824,  1.1919262 , ...,  0.77258661,
        -0.46138749, -0.49701778],
       ...,
       [-0.85524411, -0.69460048,  0.27567634, ..., -1.29110112,
         2.16192996, -0.49701778],
       [ 0.3205319 , -0.29179943,  0.74689055, ..., -1.29110112,
         2.16192996, -0.49701778],
       [-0.85524411, -1.00149651, -0.87618062, ..., -1.29110112,
         2.16192996, -0.49701778]], shape=(279, 8))

Output data:

In [32]:
data_dir = "/home/patrick/Projects/DataScienceAndMachineLearning/Data/AutoMPG-Dataset"
np.save(f"{data_dir}/train_X.npy", train_X)
np.save(f"{data_dir}/train_y.npy", train_y)
np.save(f"{data_dir}/test_X.npy", test_X)
np.save(f"{data_dir}/test_y.npy", test_y)